-- =============================================================================
-- ConectAR S.R.L. - Trabajo de Diploma - Villaverde, Agustin (575_AV)
-- 04 - T05 Diccionario de idiomas (patron Observer)
--
-- Las traducciones viven en la BD, no en archivos .resx. Agregar un idioma
-- nuevo es insertar filas (o usar SP_CrearIdioma, que clona un idioma base),
-- sin recompilar la aplicacion.
--
-- Las claves siguen el formato AMBITO_ELEMENTO (COMUN_, LOGIN_, MENU_, USU_,
-- PERF_, BIT_, CLAVE_) y son las que consumen los formularios al implementar
-- IObservadorIdioma.ActualizarTextos().
--
-- Idempotente: las traducciones de ES/EN se borran y se recargan completas.
-- =============================================================================

USE [ConectAR_DB];
GO

SET NOCOUNT ON;
GO

-- Datos: idiomas
-- -----------------------------------------------
IF NOT EXISTS (SELECT 1 FROM Idioma WHERE Codigo = 'ES')
    INSERT INTO Idioma (Codigo, Nombre) VALUES (N'ES', N'Español');
IF NOT EXISTS (SELECT 1 FROM Idioma WHERE Codigo = 'EN')
    INSERT INTO Idioma (Codigo, Nombre) VALUES (N'EN', N'English');
GO

-- -----------------------------------------------
-- Datos: traducciones (se recargan completas)
-- -----------------------------------------------
DECLARE @ES INT = (SELECT Id FROM Idioma WHERE Codigo = 'ES');
DECLARE @EN INT = (SELECT Id FROM Idioma WHERE Codigo = 'EN');

DELETE FROM Traduccion WHERE IdIdioma IN (@ES, @EN);

INSERT INTO Traduccion (IdIdioma, Clave, Texto) VALUES
-- ------------------- Comunes -------------------
(@ES, N'COMUN_ATENCION',                N'Atencion'),
(@EN, N'COMUN_ATENCION',                N'Warning'),
(@ES, N'COMUN_CONFIRMA_SALIR_APP',      N'¿Esta seguro que desea cerrar la aplicacion?'),
(@EN, N'COMUN_CONFIRMA_SALIR_APP',      N'Are you sure you want to close the application?'),
(@ES, N'COMUN_CONFIRMA_CERRAR_SESION',  N'¿Esta seguro que desea cerrar la sesion?'),
(@EN, N'COMUN_CONFIRMA_CERRAR_SESION',  N'Are you sure you want to log out?'),
(@ES, N'COMUN_ERROR_BD',                N'Error de comunicacion con la Base de Datos: '),
(@EN, N'COMUN_ERROR_BD',                N'Database communication error: '),
(@ES, N'COMUN_SALIR',                   N'Salir'),
(@EN, N'COMUN_SALIR',                   N'Exit'),
(@ES, N'COMUN_CANCELAR',                N'Cancelar'),
(@EN, N'COMUN_CANCELAR',                N'Cancel'),
(@ES, N'COMUN_GUARDAR',                 N'Guardar'),
(@EN, N'COMUN_GUARDAR',                 N'Save'),
(@ES, N'COMUN_ACEPTAR',                 N'Aceptar'),
(@EN, N'COMUN_ACEPTAR',                 N'OK'),
(@ES, N'COMUN_USUARIO',                 N'Usuario'),
(@EN, N'COMUN_USUARIO',                 N'User'),
(@ES, N'COMUN_CONTRASENA',              N'Contraseña'),
(@EN, N'COMUN_CONTRASENA',              N'Password'),
(@ES, N'COMUN_ROL',                     N'Rol'),
(@EN, N'COMUN_ROL',                     N'Role'),
(@ES, N'COMUN_NOMBRE',                  N'Nombre'),
(@EN, N'COMUN_NOMBRE',                  N'Name'),
(@ES, N'COMUN_APELLIDO',                N'Apellido'),
(@EN, N'COMUN_APELLIDO',                N'Last Name'),
(@ES, N'COMUN_FECHA',                   N'Fecha'),
(@EN, N'COMUN_FECHA',                   N'Date'),
(@ES, N'COMUN_ACCION',                  N'Accion'),
(@EN, N'COMUN_ACCION',                  N'Action'),
-- ------------------- Login -------------------
(@ES, N'LOGIN_TITULO',                  N'Login'),
(@EN, N'LOGIN_TITULO',                  N'Login'),
(@ES, N'LOGIN_BTN_INICIAR',             N'Iniciar'),
(@EN, N'LOGIN_BTN_INICIAR',             N'Sign In'),
(@ES, N'LOGIN_LNK_SIN_CONEXION',        N'Iniciar sin conexion'),
(@EN, N'LOGIN_LNK_SIN_CONEXION',        N'Start offline'),
(@ES, N'LOGIN_TIT_DATOS_INVALIDOS',     N'Datos Invalidos'),
(@EN, N'LOGIN_TIT_DATOS_INVALIDOS',     N'Invalid Data'),
(@ES, N'LOGIN_MSG_DATOS_INVALIDOS',     N'Los datos ingresados no cumplen con el formato requerido.'),
(@EN, N'LOGIN_MSG_DATOS_INVALIDOS',     N'The entered data does not meet the required format.'),
(@ES, N'LOGIN_ERR_USER_INEXISTENTE',    N'El usuario ingresado no existe'),
(@EN, N'LOGIN_ERR_USER_INEXISTENTE',    N'The entered user does not exist'),
(@ES, N'LOGIN_ERR_USER_BLOQUEADO',      N'El usuario se encuentra bloqueado. Contacte al administrador'),
(@EN, N'LOGIN_ERR_USER_BLOQUEADO',      N'The user is locked. Contact the administrator'),
(@ES, N'LOGIN_ERR_PASS_INCORRECTA',     N'La contraseña ingresada es incorrecta'),
(@EN, N'LOGIN_ERR_PASS_INCORRECTA',     N'The entered password is incorrect'),
(@ES, N'LOGIN_MSG_USER_INACTIVO',       N'El usuario -->{0}<-- no esta disponible. Contacte al administrador.'),
(@EN, N'LOGIN_MSG_USER_INACTIVO',       N'The user -->{0}<-- is not available. Contact the administrator.'),
(@ES, N'LOGIN_MSG_FIN_INTENTOS',        N'Cantidad de intentos superado, se bloqueo el usuario. Cerrando la aplicacion.'),
(@EN, N'LOGIN_MSG_FIN_INTENTOS',        N'Attempt limit exceeded, the user has been locked. Closing the application.'),
(@ES, N'LOGIN_MSG_SESION_INICIADA',     N'El usuario -->{0}<-- ya tiene la sesion iniciada.'),
(@EN, N'LOGIN_MSG_SESION_INICIADA',     N'The user -->{0}<-- already has an active session.'),
(@ES, N'LOGIN_MSG_EXISTE_SESION',       N'Ya existe una sesion iniciada, desea finalizarla?'),
(@EN, N'LOGIN_MSG_EXISTE_SESION',       N'There is already an active session, do you want to end it?'),
(@ES, N'LOGIN_MSG_SESION_CERRADA',      N'Sesion cerrada correctamente. Intente nuevamente con su usuario'),
(@EN, N'LOGIN_MSG_SESION_CERRADA',      N'Session closed successfully. Try again with your user'),
(@ES, N'LOGIN_MSG_USUARIO_EN_USO',      N'Intente nuevamente con el usuario actualmente en uso. Si no es el suyo por favor cierre la sesion'),
(@EN, N'LOGIN_MSG_USUARIO_EN_USO',      N'Try again with the user currently in use. If it is not yours, please log out'),
-- ------------------- Menu -------------------
(@ES, N'MENU_TS_INICIO',                N'Inicio'),
(@EN, N'MENU_TS_INICIO',                N'Home'),
(@ES, N'MENU_INICIAR_SESION',           N'Iniciar Sesion'),
(@EN, N'MENU_INICIAR_SESION',           N'Sign In'),
(@ES, N'MENU_CERRAR_SESION',            N'Cerrar Sesion'),
(@EN, N'MENU_CERRAR_SESION',            N'Log Out'),
(@ES, N'MENU_TS_ADMIN',                 N'Admin'),
(@EN, N'MENU_TS_ADMIN',                 N'Admin'),
(@ES, N'MENU_GESTION_USUARIOS',         N'Gestion de Usuarios'),
(@EN, N'MENU_GESTION_USUARIOS',         N'User Management'),
(@ES, N'MENU_PERFILES',                 N'Perfiles'),
(@EN, N'MENU_PERFILES',                 N'Profiles'),
(@ES, N'MENU_IDIOMAS',                  N'Idiomas'),
(@EN, N'MENU_IDIOMAS',                  N'Languages'),
(@ES, N'MENU_BACKUP',                   N'Backup'),
(@EN, N'MENU_BACKUP',                   N'Backup'),
(@ES, N'MENU_RESTORE',                  N'Restore'),
(@EN, N'MENU_RESTORE',                  N'Restore'),
(@ES, N'MENU_BITACORA',                 N'Bitacora'),
(@EN, N'MENU_BITACORA',                 N'Event Log'),
(@ES, N'MENU_CAMBIAR_CLAVE',            N'Cambiar Clave'),
(@EN, N'MENU_CAMBIAR_CLAVE',            N'Change Password'),
(@ES, N'MENU_CAMBIAR_IDIOMA',           N'Cambiar Idioma'),
(@EN, N'MENU_CAMBIAR_IDIOMA',           N'Change Language'),
(@ES, N'MENU_TS_VENTAS',                N'Ventas'),
(@EN, N'MENU_TS_VENTAS',                N'Sales'),
(@ES, N'MENU_LLENAR_CARRITO',           N'Llenar Carrito'),
(@EN, N'MENU_LLENAR_CARRITO',           N'Fill Cart'),
(@ES, N'MENU_REALIZAR_VENTA',           N'Realizar Venta'),
(@EN, N'MENU_REALIZAR_VENTA',           N'Make Sale'),
(@ES, N'MENU_TS_GESTION',               N'Gestion'),
(@EN, N'MENU_TS_GESTION',               N'Management'),
(@ES, N'MENU_CLIENTE',                  N'Cliente'),
(@EN, N'MENU_CLIENTE',                  N'Customer'),
(@ES, N'MENU_PRODUCTOS',                N'Productos'),
(@EN, N'MENU_PRODUCTOS',                N'Products'),
(@ES, N'MENU_PROVEEDORES',              N'Proveedores'),
(@EN, N'MENU_PROVEEDORES',              N'Suppliers'),
(@ES, N'MENU_TS_REPORTES',              N'Reportes'),
(@EN, N'MENU_TS_REPORTES',              N'Reports'),
(@ES, N'MENU_TS_AYUDA',                 N'Ayuda'),
(@EN, N'MENU_TS_AYUDA',                 N'Help'),
(@ES, N'MENU_LBL_USUARIO',              N'Usuario: '),
(@EN, N'MENU_LBL_USUARIO',              N'User: '),
(@ES, N'MENU_LBL_SIN_CONEXION',         N'Usuario: Sin Conexion'),
(@EN, N'MENU_LBL_SIN_CONEXION',         N'User: Offline'),
-- ------------------- Gestion de Usuarios -------------------
(@ES, N'USU_TITULO',                    N'Gestion Usuarios'),
(@EN, N'USU_TITULO',                    N'User Management'),
(@ES, N'USU_LBL_TITULO',                N'GESTIÓN DE USUARIOS'),
(@EN, N'USU_LBL_TITULO',                N'USER MANAGEMENT'),
(@ES, N'USU_LBL_OPCIONES',              N'Opciones'),
(@EN, N'USU_LBL_OPCIONES',              N'Options'),
(@ES, N'USU_GB_DATOS',                  N'Datos Usuario'),
(@EN, N'USU_GB_DATOS',                  N'User Data'),
(@ES, N'USU_GB_MENSAJES',               N'Mensajes'),
(@EN, N'USU_GB_MENSAJES',               N'Messages'),
(@ES, N'USU_LBL_DNI',                   N'DNI'),
(@EN, N'USU_LBL_DNI',                   N'ID Number'),
(@ES, N'USU_LBL_DIRECCION',             N'Direccion'),
(@EN, N'USU_LBL_DIRECCION',             N'Address'),
(@ES, N'USU_LBL_TELEFONO',              N'Telefono'),
(@EN, N'USU_LBL_TELEFONO',              N'Phone'),
(@ES, N'USU_LBL_EMAIL',                 N'E-mail'),
(@EN, N'USU_LBL_EMAIL',                 N'E-mail'),
(@ES, N'USU_CHK_ACTIVO',                N'Activo'),
(@EN, N'USU_CHK_ACTIVO',                N'Active'),
(@ES, N'USU_CHK_BLOQUEADO',             N'Bloqueado'),
(@EN, N'USU_CHK_BLOQUEADO',             N'Locked'),
(@ES, N'USU_BTN_CREAR',                 N'Crear Usuario'),
(@EN, N'USU_BTN_CREAR',                 N'Create User'),
(@ES, N'USU_BTN_MODIFICAR',             N'Modificar Usuario'),
(@EN, N'USU_BTN_MODIFICAR',             N'Edit User'),
(@ES, N'USU_BTN_ELIMINAR',              N'Eliminar Usuario'),
(@EN, N'USU_BTN_ELIMINAR',              N'Delete User'),
(@ES, N'USU_BTN_DESBLOQUEAR',           N'Desbloquear'),
(@EN, N'USU_BTN_DESBLOQUEAR',           N'Unlock'),
(@ES, N'USU_MSG_DNI_EXISTE',            N'El DNI ingresado ya cuenta con un usuario'),
(@EN, N'USU_MSG_DNI_EXISTE',            N'The entered ID number already has a user'),
(@ES, N'USU_MSG_USER_EXISTE',           N'El usuario ingresado ya existe'),
(@EN, N'USU_MSG_USER_EXISTE',           N'The entered user already exists'),
(@ES, N'USU_MSG_CREADO',                N'El usuario -- {0} -- fue creado exitosamente'),
(@EN, N'USU_MSG_CREADO',                N'User -- {0} -- was created successfully'),
(@ES, N'USU_MSG_ACTUALIZADO',           N'Usuario -- {0} -- actualizado correctamente'),
(@EN, N'USU_MSG_ACTUALIZADO',           N'User -- {0} -- updated successfully'),
(@ES, N'USU_MSG_CONFIRMA_ELIMINAR',     N'Desea eliminar el usuario -- {0} -- ?'),
(@EN, N'USU_MSG_CONFIRMA_ELIMINAR',     N'Do you want to delete user -- {0} -- ?'),
(@ES, N'USU_MSG_BAJA_OK',               N'Baja de usuario -- {0} -- exitosa'),
(@EN, N'USU_MSG_BAJA_OK',               N'User -- {0} -- deactivated successfully'),
(@ES, N'USU_MSG_CONFIRMA_DESBLOQUEO',   N'Desea continuar con el desbloqueo?'),
(@EN, N'USU_MSG_CONFIRMA_DESBLOQUEO',   N'Do you want to continue with the unlock?'),
(@ES, N'USU_TIT_DESBLOQUEAR',           N'Desbloquear Usuario'),
(@EN, N'USU_TIT_DESBLOQUEAR',           N'Unlock User'),
(@ES, N'USU_MSG_DESBLOQUEO_OK',         N'Usuario desbloqueado exitosamente'),
(@EN, N'USU_MSG_DESBLOQUEO_OK',         N'User unlocked successfully'),
(@ES, N'USU_ERR_CREAR',                 N'Ocurrio un error en la creacion de usuario: '),
(@EN, N'USU_ERR_CREAR',                 N'An error occurred while creating the user: '),
(@ES, N'USU_ERR_ACTUALIZAR',            N'Ocurrio un error en la actualizacion del usuario: '),
(@EN, N'USU_ERR_ACTUALIZAR',            N'An error occurred while updating the user: '),
(@ES, N'USU_ERR_ELIMINAR',              N'No se pudo eliminar el usuario seleccionado: '),
(@EN, N'USU_ERR_ELIMINAR',              N'The selected user could not be deleted: '),
(@ES, N'USU_ERR_ROLES',                 N'Error cargando roles desde Perfiles: '),
(@EN, N'USU_ERR_ROLES',                 N'Error loading roles from Profiles: '),
(@ES, N'USU_VAL_NOMBRE',                N'Campos Nombre y/o Apellido contienen caracteres no validos. Ingrese solo letras por favor.'),
(@EN, N'USU_VAL_NOMBRE',                N'Name and/or Last Name fields contain invalid characters. Please enter letters only.'),
(@ES, N'USU_VAL_NUMEROS',               N'Campos DNI y/o Telefono contienen caracteres no validos. Ingrese solo numeros por favor.'),
(@EN, N'USU_VAL_NUMEROS',               N'ID Number and/or Phone fields contain invalid characters. Please enter numbers only.'),
(@ES, N'USU_VAL_DIRECCION',             N'Campo Direccion contiene caracteres no validos. Ingrese solo letras y numeros por favor.'),
(@EN, N'USU_VAL_DIRECCION',             N'Address field contains invalid characters. Please enter letters and numbers only.'),
(@ES, N'USU_VAL_USUARIO',               N'Campo Usuario contiene caracteres no validos. No se permiten espacios ni caracteres especiales.'),
(@EN, N'USU_VAL_USUARIO',               N'User field contains invalid characters. Spaces and special characters are not allowed.'),
(@ES, N'USU_VAL_MAIL',                  N'Campo eMail contiene caracteres no validos. Respete el formato xxxx@xxx.xxx, sin espacios ni caracteres especiales.'),
(@EN, N'USU_VAL_MAIL',                  N'E-mail field contains invalid characters. Follow the format xxxx@xxx.xxx, without spaces or special characters.'),
-- ------------------- Bitacora -------------------
(@ES, N'BIT_TITULO',                    N'Bitacora de Eventos'),
(@EN, N'BIT_TITULO',                    N'Event Log'),
(@ES, N'BIT_LBL_TITULO',                N'EVENTOS'),
(@EN, N'BIT_LBL_TITULO',                N'EVENTS'),
(@ES, N'BIT_COL_REGISTRO',              N'ID Registro'),
(@EN, N'BIT_COL_REGISTRO',              N'Record ID'),
-- ------------------- Cambio de Clave -------------------
(@ES, N'CLAVE_TITULO',                  N'Cambiar Contraseña'),
(@EN, N'CLAVE_TITULO',                  N'Change Password'),
(@ES, N'CLAVE_LBL_ACTUAL',              N'Contraseña Actual'),
(@EN, N'CLAVE_LBL_ACTUAL',              N'Current Password'),
(@ES, N'CLAVE_LBL_NUEVA',               N'Nueva Contraseña'),
(@EN, N'CLAVE_LBL_NUEVA',               N'New Password'),
(@ES, N'CLAVE_LBL_REPETIR',             N'Repetir Contraseña'),
(@EN, N'CLAVE_LBL_REPETIR',             N'Repeat Password'),
(@ES, N'CLAVE_BTN_CONFIRMAR',           N'Confirmar'),
(@EN, N'CLAVE_BTN_CONFIRMAR',           N'Confirm'),
(@ES, N'CLAVE_MSG_INSTRUCCIONES',       N'Introduzca una contraseña distinta a la anterior. Recuerde introducir solo letras y numeros'),
(@EN, N'CLAVE_MSG_INSTRUCCIONES',       N'Enter a password different from the previous one. Remember to enter only letters and numbers'),
(@ES, N'CLAVE_ERR_INTENTOS',            N'Contraseña incorrecta, quedan {0} intentos'),
(@EN, N'CLAVE_ERR_INTENTOS',            N'Incorrect password, {0} attempts remaining'),
(@ES, N'CLAVE_MSG_BLOQUEADO',           N'Cantidad de intentos superados, usuario bloqueado. Contacte al administrador'),
(@EN, N'CLAVE_MSG_BLOQUEADO',           N'Attempt limit exceeded, user locked. Contact the administrator'),
(@ES, N'CLAVE_TIT_BLOQUEADO',           N'Usuario Bloqueado'),
(@EN, N'CLAVE_TIT_BLOQUEADO',           N'User Locked'),
(@ES, N'CLAVE_MSG_OK',                  N'Contraseña cambiada correctamente'),
(@EN, N'CLAVE_MSG_OK',                  N'Password changed successfully'),
(@ES, N'CLAVE_TIT_OK',                  N'Nueva Contraseña'),
(@EN, N'CLAVE_TIT_OK',                  N'New Password'),
(@ES, N'CLAVE_ERR_FORMATO',             N'Formato de contraseña ingresado incorrecto'),
(@EN, N'CLAVE_ERR_FORMATO',             N'Incorrect password format entered'),
(@ES, N'CLAVE_ERR_DISTINTAS',           N'Las contraseñas son distintas, vuelva a intentarlo'),
(@EN, N'CLAVE_ERR_DISTINTAS',           N'The passwords do not match, please try again'),
(@ES, N'CLAVE_ERR_IGUAL_ANTERIOR',      N'La nueva contraseña debe ser distinta a la anterior'),
(@EN, N'CLAVE_ERR_IGUAL_ANTERIOR',      N'The new password must be different from the previous one'),
(@ES, N'CLAVE_ERR_NO_FORMATO',          N'La contraseña no coincide con el formato necesario'),
(@EN, N'CLAVE_ERR_NO_FORMATO',          N'The password does not meet the required format'),
-- ------------------- Gestion de Perfiles -------------------
(@ES, N'PERF_TITULO',                   N'Gestión de Perfiles'),
(@EN, N'PERF_TITULO',                   N'Profile Management'),
(@ES, N'PERF_LBL_TITULO',               N'GESTIÓN DE PERFILES'),
(@EN, N'PERF_LBL_TITULO',               N'PROFILE MANAGEMENT'),
(@ES, N'PERF_GB_DATOS',                 N'Datos del Perfil'),
(@EN, N'PERF_GB_DATOS',                 N'Profile Data'),
(@ES, N'PERF_GB_PERMISOS',              N'Permisos y Familias Disponibles'),
(@EN, N'PERF_GB_PERMISOS',              N'Available Permissions and Families'),
(@ES, N'PERF_GB_ARBOL',                 N'Árbol de Jerarquía de Permisos'),
(@EN, N'PERF_GB_ARBOL',                 N'Permission Hierarchy Tree'),
(@ES, N'PERF_LBL_NOMBRE',               N'Nombre:'),
(@EN, N'PERF_LBL_NOMBRE',               N'Name:'),
(@ES, N'PERF_LBL_ROL_FAMILIA',          N'Rol / Familia:'),
(@EN, N'PERF_LBL_ROL_FAMILIA',          N'Role / Family:'),
(@ES, N'PERF_RB_ROL',                   N'Rol'),
(@EN, N'PERF_RB_ROL',                   N'Role'),
(@ES, N'PERF_RB_FAMILIA',               N'Familia'),
(@EN, N'PERF_RB_FAMILIA',               N'Family'),
(@ES, N'PERF_BTN_CREAR',                N'Crear'),
(@EN, N'PERF_BTN_CREAR',                N'Create'),
(@ES, N'PERF_BTN_ELIMINAR',             N'Eliminar'),
(@EN, N'PERF_BTN_ELIMINAR',             N'Delete'),
(@ES, N'PERF_MSG_SELECCION',            N'Debe seleccionar permisos o familias'),
(@EN, N'PERF_MSG_SELECCION',            N'You must select permissions or families');
GO

PRINT '04 - Idiomas y traducciones cargados.';
GO
